package java.cores;

enum Soda {
	BRISK_HALF_AND_HALF, BRISK_RASPBERRY, BRISK_LEMONADE, BRISK_SWEET_TEA,
	PEPSI, DIET_PEPSI, PEPSI_WILD_CHERRY, PEPSI_MAX,
	MOUNTAIN_DEW, DIET_MOUNTIAN_DEW, MOUNTAIN_DEW_CODE_RED, DIET_MOUNTAIN_DEW_CODE_RED,
	DIET_CRUSH, DIET_MUG
}
